// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-tools.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var SITE = "https://docunova-ai.lovable.app";
var CATEGORIES = ["organize", "convert", "edit", "ai", "image", "security", "documents"];
var TOOLS = [
  { slug: "/merge", name: "Merge PDF", category: "organize" },
  { slug: "/split", name: "Split PDF", category: "organize" },
  { slug: "/compress", name: "Compress PDF", category: "organize" },
  { slug: "/organize", name: "Organize PDF", category: "organize" },
  { slug: "/extract-pages", name: "Extract Pages", category: "organize" },
  { slug: "/remove-pages", name: "Remove Pages", category: "organize" },
  { slug: "/rotate-pdf", name: "Rotate PDF", category: "organize" },
  { slug: "/reverse-pdf", name: "Reverse PDF", category: "organize" },
  { slug: "/convert", name: "Convert PDF", category: "convert" },
  { slug: "/pdf-to-word", name: "PDF to Word", category: "convert" },
  { slug: "/word-to-pdf", name: "Word to PDF", category: "convert" },
  { slug: "/pdf-to-excel", name: "PDF to Excel", category: "convert" },
  { slug: "/excel-to-pdf", name: "Excel to PDF", category: "convert" },
  { slug: "/pdf-to-powerpoint", name: "PDF to PowerPoint", category: "convert" },
  { slug: "/powerpoint-to-pdf", name: "PowerPoint to PDF", category: "convert" },
  { slug: "/pdf-to-image", name: "PDF to Image", category: "convert" },
  { slug: "/image-to-pdf", name: "Image to PDF", category: "convert" },
  { slug: "/pdf-to-text", name: "PDF to Text", category: "convert" },
  { slug: "/pdf-to-html", name: "PDF to HTML", category: "convert" },
  { slug: "/html-to-pdf", name: "HTML to PDF", category: "convert" },
  { slug: "/pdf-to-epub", name: "PDF to EPUB", category: "convert" },
  { slug: "/edit-pdf", name: "Edit PDF", category: "edit" },
  { slug: "/sign-pdf", name: "Sign PDF", category: "edit" },
  { slug: "/add-watermark", name: "Add Watermark", category: "edit" },
  { slug: "/add-page-numbers", name: "Add Page Numbers", category: "edit" },
  { slug: "/redact-pdf", name: "Redact PDF", category: "edit" },
  { slug: "/crop-pdf", name: "Crop PDF", category: "edit" },
  { slug: "/photo-text-edit", name: "Photo Text Edit", category: "edit" },
  { slug: "/ocr", name: "OCR PDF", category: "ai" },
  { slug: "/ai-summarizer", name: "AI PDF Summarizer", category: "ai" },
  { slug: "/ai-translator", name: "AI Translator", category: "ai" },
  { slug: "/ai-rewriter", name: "AI Rewriter", category: "ai" },
  { slug: "/ai-grammar-check", name: "AI Grammar Check", category: "ai" },
  { slug: "/ai-email-writer", name: "AI Email Writer", category: "ai" },
  { slug: "/ai-cover-letter", name: "AI Cover Letter", category: "ai" },
  { slug: "/ai-blog-writer", name: "AI Blog Writer", category: "ai" },
  { slug: "/ai-idea-generator", name: "AI Idea Generator", category: "ai" },
  { slug: "/ai-code-explainer", name: "AI Code Explainer", category: "ai" },
  { slug: "/ai-math-solver", name: "AI Math Solver", category: "ai" },
  { slug: "/ai-data-extractor", name: "AI Data Extractor", category: "ai" },
  { slug: "/ai-resume-analyzer", name: "AI Resume Analyzer", category: "ai" },
  { slug: "/ai-hashtag-generator", name: "AI Hashtag Generator", category: "ai" },
  { slug: "/ai-image-enhance", name: "AI Image Enhance", category: "ai" },
  { slug: "/image-to-text", name: "Image to Text (OCR)", category: "ai" },
  { slug: "/image-compress", name: "Image Compress", category: "image" },
  { slug: "/image-resize", name: "Image Resize", category: "image" },
  { slug: "/image-crop", name: "Image Crop", category: "image" },
  { slug: "/image-rotate", name: "Image Rotate", category: "image" },
  { slug: "/remove-background", name: "Remove Background", category: "image" },
  { slug: "/jpg-to-png", name: "JPG to PNG", category: "image" },
  { slug: "/png-to-jpg", name: "PNG to JPG", category: "image" },
  { slug: "/jpg-to-webp", name: "JPG to WebP", category: "image" },
  { slug: "/webp-to-jpg", name: "WebP to JPG", category: "image" },
  { slug: "/protect-pdf", name: "Protect PDF", category: "security" },
  { slug: "/unlock-pdf", name: "Unlock PDF", category: "security" },
  { slug: "/resume-builder", name: "Resume Builder", category: "documents" },
  { slug: "/invoice-generator", name: "Invoice Generator", category: "documents" },
  { slug: "/certificate-maker", name: "Certificate Maker", category: "documents" },
  { slug: "/letter-writer", name: "Letter Writer", category: "documents" }
];
var list_tools_default = defineTool({
  name: "list_tools",
  title: "List Docunova AI tools",
  description: "List the free document, PDF, image, and AI tools available on Docunova AI. Optionally filter by category or search query.",
  inputSchema: {
    category: z.enum(CATEGORIES).optional().describe("Filter by category."),
    query: z.string().optional().describe("Case-insensitive substring match against tool name or slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query }) => {
    const q = query?.trim().toLowerCase();
    const filtered = TOOLS.filter((t) => {
      if (category && t.category !== category) return false;
      if (q && !t.name.toLowerCase().includes(q) && !t.slug.toLowerCase().includes(q)) return false;
      return true;
    }).map((t) => ({ ...t, url: `${SITE}${t.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: filtered.length, tools: filtered }, null, 2) }],
      structuredContent: { count: filtered.length, tools: filtered }
    };
  }
});

// src/lib/mcp/tools/get-tool-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_tool_info_default = defineTool2({
  name: "get_tool_info",
  title: "Get tool info",
  description: 'Get details about a single Docunova AI tool by its slug (e.g. "/merge", "/ai-translator").',
  inputSchema: {
    slug: z2.string().min(1).describe("Tool slug starting with '/', e.g. '/merge'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const normalized = slug.startsWith("/") ? slug : `/${slug}`;
    const tool = TOOLS.find((t) => t.slug === normalized);
    if (!tool) {
      return {
        content: [{ type: "text", text: `No tool found for slug "${normalized}". Use list_tools to discover valid slugs.` }],
        isError: true
      };
    }
    const info = {
      ...tool,
      url: `${SITE}${tool.slug}`,
      description: `${tool.name} \u2014 free, private, in-browser. No signup, no watermark, no file-size limit.`,
      pricing: "Free forever",
      privacy: "Processed entirely in the user's browser when possible; AI tools use Docunova AI's secure gateway."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/site-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var site_info_default = defineTool3({
  name: "site_info",
  title: "Docunova AI site info",
  description: "Get high-level public information about Docunova AI: what it is, main URL, contact, and top categories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Docunova AI Suite",
      url: SITE,
      tagline: "Free AI-powered PDF, document, image, and text tools \u2014 no signup, no watermark, no file-size limit.",
      contact_email: "documentai999@gmail.com",
      categories: ["organize", "convert", "edit", "ai", "image", "security", "documents"],
      pricing: "Free forever",
      founder: "Aman Vishwakarma"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nqqnwepqyogrixjdbxev";
var mcp_default = defineMcp({
  name: "docunova-ai-mcp",
  title: "Docunova AI Suite MCP",
  version: "0.2.0",
  instructions: "Tools for exploring the Docunova AI Suite \u2014 a free platform of 100+ PDF, document, image, and AI text tools. Callers sign in as a Docunova AI user; only public catalog data is returned. Use `list_tools` to browse (optionally filtered by category/query), `get_tool_info` to look up a single tool by slug, and `site_info` for high-level site facts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tools_default, get_tool_info_default, site_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
